### ISSUE TITLE
Queue appears to be empty while it says there 3 more

### ISSUE THREAD

**Issue by couci** [mozilla/m-response#281] opened 2019-07-04 12:40 UTC
On the dashboard it says there 3 more responses to be moderated. When I click to moderate there is an error.

**Comment by madasan** [comment] 2019-07-08 16:00
[STR]:
1. Open https://respond.mozilla.community/dashboard
2. Check numbers on both Respond and Moderate queues
3. Go to either queues and skip through reviews/responses

[Expected result]:
The number of reviews/responses that you skip through should correspond to the number initially showed on the queue

[Actual result]:
There's less reviews/responses than the number shown.

![image](https://user-images.githubusercontent.com/10244340/60824472-50998600-a1b2-11e9-8f0f-730a035417ef.png)

**Comment by rleitan** [comment] 2019-07-18 11:03
I can see 404 error in the console 
<img width="776" alt="2019-07-18_13h58_56" src="https://user-images.githubusercontent.com/41474886/61452581-c517b600-a964-11e9-91c9-bef230bce75a.png">

**Comment by viorelaioia** [comment] 2019-10-31 12:54
@madasan , is this a duplicate of https://github.com/mozilla/m-response/issues/406?

**Closed** 2020-07-03 10:19 UTC
Labels: Estimate: 8 hours, Investigate, P1
