### ISSUE TITLE
Removing duplicate reviews by the same person

### ISSUE THREAD

**Issue by decode-dev** [mozilla/m-response#277] opened 2019-07-03 22:38 UTC
Is there any way to delete or make sure to have non-duplicate reviews in the tool since I did find them last time and also in the new tool.
Like there were same review by same people in the queue
Ex : 
A Person
This is not good , not working
A person
This is not good, not working.

**Comment by madasan** [comment] 2019-07-08 14:43
Cannot reproduce this one, will close it for now.

**Closed by madasan** 2019-07-08 14:43 UTC
