### ISSUE TITLE
Invisible avatars

### ISSUE THREAD

**Issue by mcroud** [mozilla/m-response#274] opened 2019-06-21 18:38 UTC
A user's avatar is never directly shown.
The avatar only becomes partially visible when a user hovers over the profile icon on the dashboard or over the avatar icon in their profile.

![Untitled3](https://user-images.githubusercontent.com/42435754/59944089-c4007100-9418-11e9-9432-007fc7189773.gif)

**Comment by madasan** [comment] 2019-07-08 14:48
This looks like a duplicate of #285. Please see the other ticket.

**Closed by madasan** 2019-07-08 14:48 UTC
