### ISSUE TITLE
"Staff approved" checkbox is not updated in admin interface when the staff approval is deleted

### ISSUE THREAD

**Issue by rleitan** [mozilla/m-response#320] opened 2019-07-15 12:10 UTC
[Precondition]:
Add 2 approvals to a response ( one from a 1st level account  and one from a 2nd level account)
The response has: Approved by staff status

[STR]:
1.Go to admin interface and select the response from precondition
2.Click delete button
3.Click to edit the approvals
4.Delete the approval made by the 2nd level account

[Expected result]:
The response status should be updated. The Staff approved checkbox should be not checked

[Actual result]:
The approval is deleted and the response it's updated properly. But the Staff approved checkbox is still checked

**Comment by johngian** [comment] 2019-10-28 13:30
@madasan This is not a user-facing bug. In order to reproduce this it implies that somebody with admin access is going to remove a response from /admin

Is this a flow we support? Django admin doesn't necessarily follow the logic we have in the rest of the website because its more of a low level tool. Although it can be fixed I am not sure if it worths the time in case admins shouldn't delete stuff in the first place.

Thoughts ?

**Comment by madasan** [comment] 2019-11-01 13:08
This looks like an edge case, I'm going to close it for now

**Closed by madasan** 2019-11-01 13:08 UTC
Labels: bug
