### ISSUE TITLE
More/Less link from Moderate are not working as expected

### ISSUE THREAD

**Issue by rleitan** [mozilla/m-response#313] opened 2019-07-11 12:34 UTC
[Precondition]:
Log in

[STR]:
1.Go to https://mresponse-staging.herokuapp.com/moderate/
2.Click on More/Less link displayed in the response box

[Expected result]:
Should be displayed "More" or "Less" of response

[Actual result]:
The displayed response is the same, the difference is that when More link is displayed, the three dots are also displayed after the text 

![2019-07-11_15h30_12](https://user-images.githubusercontent.com/41474886/61051315-6648be80-a3f1-11e9-97bb-9492fe8f50ff.png)

**Comment by madasan** [comment] 2020-07-06 09:56
Closing this as duplicate of https://github.com/mozilla/m-response/issues/472

**Closed by madasan** 2020-07-06 09:56 UTC
